apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "icn-kms-node.application.name" . }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: {{ template "icn-kms-node.application.name" . }}
