nameOverride: icn-kms-node-pentest
ingress:
  host: kms-pentest.staging.icapitalnetwork.com
  public: true
  tlsSecretName: stg-wildcard-cert
application:
  external_secrets:
    - staging/icn-kms-node/us-east-1
  env:
    AWS_REGION: us-east-1
    AWS_ACCOUNT: staging
    PGTZ: UTC
    FEATURE_STAGING: "false"
    NODE_ENV: production
    PORT: 3000
    NUM_WORKERS: 8
#    DEBUG: "kms:*"
#  iamRole: arn:aws:iam::445297264202:role/kms-feature-staging
  iamRole: arn:aws:iam::561705098265:role/icn_kms_staging
  image:
    repository: 445297264202.dkr.ecr.us-east-1.amazonaws.com/icn-kms-node/app
    tag: staging-56183ac1e419c0a5b8aaa06f62a138161e7908f4
  replicas: 4
node:
  resources:
    cpu:
      request: 120m
      limit: 1000m
    memory:
      request: 1024Mi
      limit: 2048Mi
nginx:
  image:
    repository: nginx
    tag: 1.20.1-alpine
  resources:
    cpu:
      request: 60m
      limit: 250m
    memory:
      request: 64Mi
      limit: 256Mi
  tls:
    secretName: stg-wildcard-cert
    certFileLocation: /etc/ssl/certs
    keyFileLocation: /etc/ssl/private
