ingress:
  host: kms.icapitalnetwork.com
  public: true
  tlsSecretName: prod-wildcard-cert
application:
  external_secrets:
    - production/icn-kms-node/us-east-1
  env:
    AWS_REGION: us-east-1
    AWS_ACCOUNT: production
    PGTZ: UTC
    FEATURE_STAGING: "false"
    NODE_ENV: production
    PORT: 3000
    NUM_WORKERS: 8
  iamRole: arn:aws:iam::561705098265:role/icn_kms_production
  image:
    repository: 445297264202.dkr.ecr.us-east-1.amazonaws.com/icn-kms-node/app
    tag: master-5a958dc2ee18ebba3c5ff94507c43573717fab78
  replicas: 4
node:
  resources:
    cpu:
      request: 120m
      limit: 1000m
    memory:
      request: 1024Mi
      limit: 2048Mi
nginx:
  image:
    repository: nginx
    tag: 1.20.1-alpine
  resources:
    cpu:
      request: 60m
      limit: 250m
    memory:
      request: 64Mi
      limit: 256Mi
  tls:
    secretName: prod-wildcard-cert
    certFileLocation: /etc/ssl/certs
    keyFileLocation: /etc/ssl/private
