---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ template "icn-kms-node.application.name" . }}
spec:
  backendType: secretsManager
  dataFrom:
    {{- range .Values.application.external_secrets }}
    - {{ . }}
    {{- end }}
