---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "icn-kms-node.nginx.name" . }}
data:
  default.conf.template: |-
    upstream app {
      server 127.0.0.1:3000;
    }

    server {
      listen 80;
      server_name ${SERVER_NAME};
      return 301 https://$host$request_uri;
      server_tokens off;
    }

    server {
      listen 443 ssl;
      server_name ${SERVER_NAME};
      server_tokens off;

      ssl_certificate      ${NGINX_SSL_CERT};
      ssl_certificate_key  ${NGINX_SSL_KEY};
      ssl_session_cache shared:ssl_cache:400000;
      root /opt/assets;

      add_header Strict-Transport-Security "max-age=15768000; includeSubDomains" always;
      add_header X-Content-Type-Options "nosniff";

      location ^~ public/assets {
        gzip_static on;
        expires max;
        add_header Cache-Control public;
        add_header Strict-Transport-Security "max-age=15768000; includeSubDomains" always;
        add_header X-Content-Type-Options "nosniff";
        if ($request_method ~* "(GET)") {
          add_header 'Access-Control-Allow-Origin' *;
          add_header Strict-Transport-Security "max-age=15768000; includeSubDomains" always;
          add_header X-Content-Type-Options "nosniff";
        }
      }

      location /assets {
        root /app/public;
        gzip_static on;
        gzip on;
        expires max;
        add_header Cache-Control public;
        add_header Strict-Transport-Security "max-age=15768000; includeSubDomains" always;
        add_header X-Content-Type-Options "nosniff";
        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Methods' 'POST, GET, PUT, DELETE, OPTIONS';
        add_header 'Access-Control-Allow-Headers' 'Authorization, Content-Type, Accept';
        add_header 'Access-Control-Allow-Credentials' 'true';
      }

      location /packs {
        root /app/public;
        gzip_static on;
        gzip on;
        expires max;
        add_header Cache-Control public;
        add_header Strict-Transport-Security "max-age=15768000; includeSubDomains" always;
        add_header X-Content-Type-Options "nosniff";
        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Methods' 'POST, GET, PUT, DELETE, OPTIONS';
        add_header 'Access-Control-Allow-Headers' 'Authorization, Content-Type, Accept';
        add_header 'Access-Control-Allow-Credentials' 'true';
      }

      try_files $uri/index.html $uri @app;

      location @app {
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_redirect off;
        proxy_set_header X-Forwarded-Proto https;
        proxy_pass http://app;
        add_header Strict-Transport-Security "max-age=15768000; includeSubDomains" always;
        add_header X-Content-Type-Options "nosniff";

        proxy_read_timeout 300;
        proxy_connect_timeout 300;
        proxy_send_timeout 300;

        if ($request_method ~* "(GET)") {
          add_header 'Access-Control-Allow-Origin' *;
          add_header Strict-Transport-Security "max-age=15768000; includeSubDomains" always;
          add_header X-Content-Type-Options "nosniff";
        }
      }

      error_page 500 502 503 504 /500.html;
      client_max_body_size 50M;
      keepalive_timeout 10;
    }
